menu:
  Archives: /archives
  Categories: /categories
  About: /about
  RSS: /atom.xml

# Table of contents | 文章目录
toc:
  on: true
  list_number: false # 目录序号
  max_depth: 3  # 1 - 6 (h1-h6) 目录最大级数

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: true
disqus_shortname: kidhaibara

# google analytics
googleTrackId: G-J38N5N288S

# whether to show read more button when showing article in excerpt in main page
read_more_btn: true
